name: Checkmarx SAST Scan
	on:
	  push:
	    branches:
	      - main
	      - master
	    
	jobs:
	  build:
	    runs-on: ubuntu-latest
	    steps:
	    - name: Checkout
	      uses: actions/checkout@v2
	    - name: Checkmarx CxFlow Action
	      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.2 #Github Action version
	      with:
	        project: BookStore-push # <-- Insert Checkmarx SAST Project Name
	        team: /CxServer/Finanzas
	        checkmarx_url: ${{ secrets.CHECKMARX_SERVER }} # To be stored in GitHub Secrets.
	        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }} # To be stored in GitHub Secrets.
	        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
	        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.
	        #checkmarx_url: http://ronenlab.ngrok.io

	        #checkmarx_username: develop1
	        #checkmarx_password: General123!
	        #checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
	        break_build: false
	        scanners: sast
	        bug_tracker: Sarif
	        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
	    - name: Upload SARIF file
	      uses: github/codeql-action/upload-sarif@v1
	      with:
	        sarif_file: cx.sarif
